# Generated by Django 6.1 on 2026-09-11 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_prenda_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composicion', models.CharField(help_text='Ej: 100% Algodón Peinado 24/1', max_length=200, verbose_name='Composición Textil')),
                ('cuidados', models.TextField(help_text='Ej: Lavar con agua fría, secar a la sombra, no usar lejía', verbose_name='Instrucciones de Cuidado')),
                ('pais_origen', models.CharField(default='Perú', max_length=60, verbose_name='País de Origen')),
                ('guia_medidas', models.TextField(blank=True, help_text='Ej: Pecho: 56cm | Largo: 74cm | Manga: 22cm', verbose_name='Guía de Medidas / Dimensiones')),
                ('prenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='store.prenda', verbose_name='Prenda')),
            ],
            options={
                'verbose_name': 'Detalle de Prenda',
                'verbose_name_plural': 'Detalles de Prendas',
            },
        ),
    ]
