# Generated by Django 6.1 on 2026-09-11 18:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_detalleprenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResenaPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('calificacion', models.PositiveSmallIntegerField(help_text='Puntuación del 1 al 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (Estrellas)')),
                ('comentario', models.TextField(verbose_name='Comentario u Opinión')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='store.prenda', verbose_name='Prenda calificada')),
            ],
            options={
                'verbose_name': 'Reseña de Prenda',
                'verbose_name_plural': 'Reseñas de Prendas',
                'ordering': ['-fecha'],
            },
        ),
    ]
