# Generated by Django 6.1 on 2026-09-11 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_resenaprenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio Unitario (S/)')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Agregado')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='store.prenda', verbose_name='Prenda')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Pedido')),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('cliente_email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Pago'), ('Pagado', 'Pagado / En Preparación'), ('Enviado', 'Enviado en Reparto'), ('Entregado', 'Entregado al Cliente'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('prendas', models.ManyToManyField(related_name='pedidos', through='store.DetallePedido', to='store.prenda', verbose_name='Prendas Incluidas')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='store.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together={('pedido', 'prenda')},
        ),
    ]
