# Generated by Django 6.1 on 2026-09-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='logistics.categoriainsumo', verbose_name='Categoría Asignada'),
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.PositiveIntegerField(verbose_name='Cantidad Despachada')),
                ('costo_unitario_historico', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo Unitario Histórico (S/)')),
                ('lote_produccion', models.CharField(default='LOTE-001', max_length=30, verbose_name='Número de Lote')),
                ('observaciones', models.CharField(blank=True, max_length=200, verbose_name='Notas de Recepción')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_despacho', to='logistics.material', verbose_name='Material Textil')),
            ],
            options={
                'verbose_name': 'Detalle de Despacho',
                'verbose_name_plural': 'Detalles de Despacho',
            },
        ),
        migrations.CreateModel(
            name='FichaTecnicaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composicion', models.CharField(default='100% Algodón Peruano', max_length=150, verbose_name='Composición Textil')),
                ('densidad_gramaje', models.CharField(default='220 gr/m²', max_length=60, verbose_name='Densidad / Gramaje')),
                ('tolerancia_encogimiento', models.CharField(default='+/- 3%', max_length=40, verbose_name='Tolerancia de Encogimiento')),
                ('temperatura_lavado', models.CharField(default='Máximo 30°C', max_length=60, verbose_name='Temperatura de Lavado')),
                ('cuidados_adicionales', models.TextField(blank=True, default='No usar lejía. Secar a la sombra en superficie plana.', verbose_name='Cuidados Adicionales')),
                ('fecha_emision_certificado', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='logistics.material', verbose_name='Material Textil')),
            ],
            options={
                'verbose_name': 'Ficha Técnica de Material',
                'verbose_name_plural': 'Fichas Técnicas de Materiales',
            },
        ),
        migrations.CreateModel(
            name='OrdenDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Despacho')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('En Tránsito', 'En Tránsito'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Borrador', max_length=20, verbose_name='Estado de Despacho')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones de Guía')),
                ('materiales', models.ManyToManyField(related_name='ordenes_despacho', through='logistics.DetalleDespacho', to='logistics.material', verbose_name='Materiales Despachados')),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='logistics.sucursal', verbose_name='Sucursal de Destino')),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to='logistics.transportista', verbose_name='Transportista Asignado')),
            ],
            options={
                'verbose_name': 'Orden de Despacho',
                'verbose_name_plural': 'Órdenes de Despacho',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.AddField(
            model_name='detalledespacho',
            name='despacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistics.ordendespacho', verbose_name='Orden de Despacho'),
        ),
        migrations.AlterUniqueTogether(
            name='detalledespacho',
            unique_together={('despacho', 'material')},
        ),
    ]
